[package]
name = "ida-rs"
version = "0.1.0"
authors = ["John Hughes <jondo2010@gmail.com>"]
edition = "2018"

[features]
default   = ["ndarray-linalg/netlib"]

[dependencies]
failure        = { version = "0.1.5" }
ndarray        = { version = "0.12.1", default-features = false }
ndarray-linalg = { version = "0.10.0",  default-features = false, optional = true }
num-traits = "0.2.6"
